/** @type {import('tailwindcss').Config} */
// Theme lifted verbatim from the Stitch export (stitch_export/DESIGN.md + code.html).
// "Context-MCP Deep Tech" — Midnight Rose on obsidian. Do not retune colors here.
module.exports = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#be0a1f",
        tertiary: "#ffb4ac",
        "secondary-fixed": "#ffdad7",
        "border-subtle": "#2D1416",
        "surface-container-low": "#24191a",
        "secondary-fixed-dim": "#ffb3af",
        "tertiary-container": "#c94d45",
        "surface-container-highest": "#3e3233",
        secondary: "#ffb3af",
        "on-error-container": "#ffdad6",
        "primary-fixed-dim": "#ffb3ad",
        background: "#1b1112",
        outline: "#ac8885",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#881e1b",
        "on-primary": "#68000a",
        "surface-bright": "#433638",
        "primary-container": "#e12d33",
        "surface-container-lowest": "#150c0d",
        "surface-muted": "#160A0B",
        "secondary-container": "#862628",
        "on-tertiary-container": "#ffffff",
        error: "#ffb4ab",
        "text-primary": "#FFFFFF",
        "on-surface": "#f2dee0",
        "on-primary-container": "#ffffff",
        "on-primary-fixed-variant": "#930013",
        "on-secondary-fixed-variant": "#832426",
        "on-secondary-container": "#ff9e9a",
        "on-tertiary": "#680208",
        "tertiary-fixed": "#ffdad6",
        surface: "#1b1112",
        "on-primary-fixed": "#410004",
        "blood-red": "#9E2029",
        "text-muted": "#888888",
        "outline-variant": "#5c403d",
        "inverse-on-surface": "#3a2d2f",
        "on-surface-variant": "#e5bdba",
        "surface-container-high": "#332729",
        "surface-container": "#281d1e",
        "surface-dim": "#1b1112",
        "surface-tint": "#ffb3ad",
        "primary-fixed": "#ffdad7",
        "surface-variant": "#3e3233",
        primary: "#ffb3ad",
        "on-secondary-fixed": "#410005",
        "tertiary-fixed-dim": "#ffb4ac",
        "on-secondary": "#640b12",
        "inverse-surface": "#f2dee0",
        "on-background": "#f2dee0",
        "on-error": "#690005",
        "on-tertiary-fixed": "#410002",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        base: "8px",
        "stack-sm": "12px",
        "margin-mobile": "16px",
        "section-gap": "120px",
        gutter: "24px",
        "container-max": "1200px",
        "stack-md": "24px",
      },
      fontFamily: {
        "display-lg": ["Space Grotesk"],
        "label-caps": ["JetBrains Mono"],
        "headline-lg-mobile": ["Space Grotesk"],
        "body-md": ["IBM Plex Sans"],
        "code-sm": ["JetBrains Mono"],
        "headline-lg": ["Space Grotesk"],
      },
      fontSize: {
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "code-sm": ["14px", { lineHeight: "1.5", fontWeight: "450" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
      },
      maxWidth: {
        "container-max": "1200px",
      },
    },
  },
  plugins: [],
};
