// Generate all 4 output formats + the single agent file (DESIGN.md)
import type { AnalyzedDesign } from './css-analyzer'

function slug(name: string): string {
  return name.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '').replace(/-+/g, '-')
}

export interface NarrativeLayer {
  overview: string
  style_tags: string[]
  components: { name: string; description: string }[]
  dos: string[]
  donts: string[]
}

// ─── DESIGN.md (agent file) ───────────────────────────────────────────────

export function toDesignMd(
  d: AnalyzedDesign,
  brand: { name: string; industry: string | null; description: string | null },
  url: string,
  narrative: NarrativeLayer,
): string {
  const colors = d.colors
  const neutrals = colors.filter(c => c.group === 'neutrals')
  const brand_colors = colors.filter(c => c.group === 'brand')
  const semantic = colors.filter(c => c.group === 'semantic')

  const colorSection = (label: string, list: typeof colors) =>
    list.length === 0 ? '' :
    `### ${label}\n${list.map(c =>
      `- \`${c.hex}\` **${c.name}**${c.cssVar ? ` (${c.cssVar})` : ''} — ${c.usage || `Used ${c.frequency}×`}`
    ).join('\n')}\n`

  const spacingTable = d.spacing.named.map(s => `| ${s.name.padEnd(5)} | ${s.value} |`).join('\n')
  const radiusTable = d.border_radius.named.map(r => `| ${r.name.padEnd(5)} | ${r.value} |`).join('\n')
  const bpTable = d.breakpoints.map(b => `| ${b.name.padEnd(4)} | ${b.value} |`).join('\n')
  const typeTable = d.typography.type_scale.map(t =>
    `| ${t.role.padEnd(12)} | ${t.size.padEnd(8)} | ${(t.weight ?? '—').toString().padEnd(7)} |`
  ).join('\n')

  const dosDonts = (narrative.dos.length || narrative.donts.length) ? `
## Do's and Don'ts

### ✓ Do
${narrative.dos.map(d => `- ${d}`).join('\n')}

### ✗ Don't
${narrative.donts.map(d => `- ${d}`).join('\n')}
` : ''

  const components = narrative.components.length ? `
## Components

${narrative.components.map(c => `### ${c.name}\n${c.description}`).join('\n\n')}
` : ''

  return `# ${brand.name} — DESIGN.md

> ${narrative.overview}

**Source:** ${url}
**Industry:** ${brand.industry || 'Unknown'}
**Design System:** ${d.design_system_detected || 'Custom'}
**Style:** ${narrative.style_tags.join(' · ')}

---

## Colors
${colorSection('Neutrals', neutrals)}${colorSection('Brand', brand_colors)}${colorSection('Semantic', semantic)}
---

## Typography

**Font${d.typography.font_families.length > 1 ? 's' : ''}:** ${d.typography.font_families.slice(0,3).join(', ') || 'system-ui'}
**Weights:** ${d.typography.font_weights.join(', ')}

| Role         | Size     | Weight  |
|--------------|----------|---------|
${typeTable || '| Body         | 16px     | 400     |'}
${d.typography.line_heights.length ? `\n**Line Heights:** ${d.typography.line_heights.slice(0,4).join(', ')}` : ''}
${d.typography.font_sources.length ? `\n**Loaded from:** ${d.typography.font_sources[0]}` : ''}

---

## Spacing

**Base unit:** ${d.spacing.base_unit}

| Token | Value |
|-------|-------|
${spacingTable || '| md    | 16px  |'}

---

## Border Radius

| Token | Value |
|-------|-------|
${radiusTable || '| md    | 8px   |'}

---

## Shadows

${d.shadows.length ? d.shadows.map(s => `\`\`\`css\nbox-shadow: ${s};\n\`\`\``).join('\n\n') : '_No significant shadows detected._'}

---

## Breakpoints

${d.breakpoints.length ? `| Name | Value |\n|------|-------|\n${bpTable}` : '_None detected._'}

---

## Transitions

${d.transitions.durations.length ? `**Durations:** ${d.transitions.durations.join(', ')}  ` : ''}
${d.transitions.easing.length ? `**Easing:** ${d.transitions.easing.join(', ')}` : ''}
${components}${dosDonts}
---

_Generated by [Context MCP](https://context-mcp-psi.vercel.app) — frequency-based CSS analysis_
`
}

// ─── Tailwind v4 ──────────────────────────────────────────────────────────

export function toTailwindV4(d: AnalyzedDesign): string {
  const colorLines = d.colors.map(c => `  --color-${slug(c.name)}: ${c.hex};`)
  const fontLines = d.typography.font_families.slice(0, 3).map((f, i) =>
    `  --font-${['sans','serif','mono'][i] || `f${i}`}: "${f}";`
  )
  const spacingLines = d.spacing.named.map(s => `  --spacing-${s.name}: ${s.value};`)
  const radiusLines = d.border_radius.named.map(r => `  --radius-${r.name}: ${r.value};`)

  return `/* Tailwind CSS v4 — paste into your CSS entry file */
@import "tailwindcss";

@theme {
  /* ── Colors ── */
${colorLines.join('\n')}

  /* ── Typography ── */
${fontLines.join('\n')}

  /* ── Spacing ── */
${spacingLines.join('\n')}

  /* ── Border Radius ── */
${radiusLines.join('\n')}

  /* Design System: ${d.design_system_detected || 'Custom'} */
  /* Base unit: ${d.spacing.base_unit} */
}`
}

// ─── CSS Variables ────────────────────────────────────────────────────────

export function toCssVariables(d: AnalyzedDesign): string {
  const colorLines = d.colors.map(c =>
    `  --color-${slug(c.name)}: ${c.hex}; /* ${c.usage || c.group} */`
  )
  const fontLines = d.typography.font_families.slice(0, 3).map((f, i) =>
    `  --font-${['primary','secondary','mono'][i] || `f${i}`}: "${f}";`
  )
  const sizeLines = d.typography.type_scale.map(t =>
    `  --text-${slug(t.role)}: ${t.size};`
  )
  const weightLines = d.typography.font_weights.map(w =>
    `  --weight-${w}: ${w};`
  )
  const spacingLines = d.spacing.named.map(s => `  --space-${s.name}: ${s.value};`)
  const radiusLines = d.border_radius.named.map(r => `  --radius-${r.name}: ${r.value};`)
  const shadowLines = d.shadows.map((s, i) => `  --shadow-${i+1}: ${s};`)

  return `:root {
  /* ════════════════════
     Colors
     ════════════════════ */
${colorLines.join('\n')}

  /* ════════════════════
     Typography
     ════════════════════ */
${fontLines.join('\n')}
${sizeLines.length ? '\n' + sizeLines.join('\n') : ''}
${weightLines.length ? '\n' + weightLines.join('\n') : ''}

  /* ════════════════════
     Spacing
     ════════════════════ */
${spacingLines.join('\n')}

  /* ════════════════════
     Border Radius
     ════════════════════ */
${radiusLines.join('\n')}

  /* ════════════════════
     Shadows
     ════════════════════ */
${shadowLines.join('\n')}
}`
}

// ─── Design Tokens JSON (W3C) ─────────────────────────────────────────────

export function toDesignTokensJson(
  d: AnalyzedDesign,
  brand: { name: string; industry: string | null },
): object {
  const colorTokens: Record<string, object> = {}
  d.colors.forEach(c => {
    colorTokens[slug(c.name)] = {
      $type: 'color',
      $value: c.hex,
      $description: c.usage || `${c.group} color, used ${c.frequency}×`,
      ...(c.cssVar ? { $extensions: { cssVar: c.cssVar } } : {}),
    }
  })

  const fontFamilyTokens: Record<string, object> = {}
  const labels = ['primary', 'secondary', 'mono']
  d.typography.font_families.slice(0, 3).forEach((f, i) => {
    fontFamilyTokens[labels[i] || `font${i}`] = { $type: 'fontFamily', $value: f }
  })

  const fontWeightTokens: Record<string, object> = {}
  d.typography.font_weights.forEach(w => {
    fontWeightTokens[`weight${w}`] = { $type: 'fontWeight', $value: w }
  })

  const fontSizeTokens: Record<string, object> = {}
  d.typography.type_scale.forEach(t => {
    fontSizeTokens[slug(t.role)] = { $type: 'dimension', $value: t.size }
  })

  const spacingTokens: Record<string, object> = {}
  d.spacing.named.forEach(s => {
    spacingTokens[s.name] = { $type: 'dimension', $value: s.value }
  })

  const radiusTokens: Record<string, object> = {}
  d.border_radius.named.forEach(r => {
    radiusTokens[r.name] = { $type: 'dimension', $value: r.value }
  })

  const shadowTokens: Record<string, object> = {}
  d.shadows.forEach((s, i) => {
    shadowTokens[`shadow${i+1}`] = { $type: 'shadow', $value: s }
  })

  return {
    $metadata: {
      source: 'Context MCP',
      method: d.method,
      brand: brand.name,
      industry: brand.industry,
      design_system: d.design_system_detected,
      generated: new Date().toISOString(),
    },
    color: colorTokens,
    typography: {
      fontFamily: fontFamilyTokens,
      fontWeight: fontWeightTokens,
      fontSize: fontSizeTokens,
    },
    spacing: spacingTokens,
    borderRadius: radiusTokens,
    shadow: shadowTokens,
  }
}
